### ISSUE TITLE
Tooltip text cut off

### ISSUE THREAD

**Issue by GoncaloGarcia** [yanivam/react-path-tooltip#37]
I'm using your react-svg-maps project to create a map containing people living in a certain country. When the number of people in the country is too large, the tooltip cuts off the text.

It would be better if the text were wrapped or if the tooltip extended to match the content.

Example below:
![image](https://user-images.githubusercontent.com/1028326/102014839-01189b80-3d50-11eb-871e-20f28899dbf6.png)

**Comment by yanivam** [comment]
Fair point, will start addressing this issue immediately. Thank you for bringing this to my attention, did not realize this was a use case for this map, I figured it would be all formatted number values but this makes sense and needs what you suggest.
